package dev.hossain.highlight.screenshot

import org.json.JSONObject

/**
 * Loads the per-language code snippets and their captured highlight.js HTML output for
 * Roborazzi screenshot tests.
 *
 * The snippet text comes from `src/test/resources/highlight-fixtures/snippets.json` (the
 * single source of truth). The highlighted HTML comes from `<name>.html` in the same
 * directory and is regenerated by `./gradlew :compose-highlight:refreshHljsFixtures`,
 * which runs the bundled `highlight.min.js` against each snippet. See
 * `compose-highlight/SCREENSHOT_TESTS.md` for the full workflow.
 */
internal object TestSnippets {
    /** Name -> Snippet for every entry in snippets.json. Lazily loaded once per JVM. */
    private val all: Map<String, Snippet> by lazy { loadAll() }

    /** Returns the snippet for [name] (e.g. `"kotlin_sample"`), or throws if not found. */
    fun load(name: String): Snippet =
        all[name] ?: error(
            "Unknown snippet '$name'. Add it to snippets.json and run " +
                "`./gradlew :compose-highlight:refreshHljsFixtures` to regenerate fixtures.",
        )

    private fun loadAll(): Map<String, Snippet> {
        val manifestText = readResource(MANIFEST_RESOURCE)
        val manifest = JSONObject(manifestText)
        val out = mutableMapOf<String, Snippet>()
        for (key in manifest.keys()) {
            val entry = manifest.getJSONObject(key)
            val language = entry.getString("language")
            val code = entry.getString("code")
            val highlightedHtml = readResource("$FIXTURES_RESOURCE_DIR/$key.html")
            out[key] = Snippet(name = key, language = language, code = code, highlightedHtml = highlightedHtml)
        }
        return out
    }

    private fun readResource(resourcePath: String): String {
        val stream =
            TestSnippets::class.java.classLoader?.getResourceAsStream(resourcePath)
                ?: error(
                    "Test resource '$resourcePath' not found on the classpath. Did you forget to run " +
                        "`./gradlew :compose-highlight:refreshHljsFixtures`?",
                )
        return stream.bufferedReader().use { it.readText() }
    }

    private const val FIXTURES_RESOURCE_DIR = "highlight-fixtures"
    private const val MANIFEST_RESOURCE = "$FIXTURES_RESOURCE_DIR/snippets.json"
}

/**
 * One screenshot fixture: the source snippet plus the HTML token tree that the bundled
 * highlight.js produces for it. Tests inject [highlightedHtml] into the WebView's pending
 * `evaluateJavascript` callback to short-circuit the live engine round-trip.
 */
internal data class Snippet(
    val name: String,
    val language: String,
    val code: String,
    val highlightedHtml: String,
)
